/* eslint-disable @typescript-eslint/no-deprecated -- tseslint.config() is the only way to use extends; core defineConfig has incompatible API */
import { includeIgnoreFile } from "@eslint/config-helpers";
import eslint from "@eslint/js";
import eslintPluginPrettier from "eslint-plugin-prettier/recommended";
import eslintPluginAstro from "eslint-plugin-astro";
import pluginReact from "eslint-plugin-react";
import reactCompiler from "eslint-plugin-react-compiler";
import eslintPluginReactHooks from "eslint-plugin-react-hooks";
import path from "node:path";
import tseslint from "typescript-eslint";

const gitignorePath = path.resolve(import.meta.dirname, ".gitignore");

const baseConfig = tseslint.config({
  extends: [eslint.configs.recommended, tseslint.configs.strictTypeChecked, tseslint.configs.stylisticTypeChecked],
  languageOptions: {
    parserOptions: {
      projectService: true,
      tsconfigRootDir: import.meta.dirname,
    },
  },
  rules: {
    "no-console": "warn",
    "no-unused-vars": "off",
    "@typescript-eslint/no-unused-vars": [
      "error",
      {
        argsIgnorePattern: "^_",
        varsIgnorePattern: "^_",
        caughtErrorsIgnorePattern: "^_",
        destructuredArrayIgnorePattern: "^_",
        ignoreRestSiblings: true,
      },
    ],
    "@typescript-eslint/restrict-template-expressions": ["error", { allowNumber: true }],
    "@typescript-eslint/no-misused-promises": ["error", { checksVoidReturn: { attributes: false } }],
  },
});

const reactConfig = tseslint.config({
  files: ["**/*.{js,jsx,ts,tsx}"],
  extends: [pluginReact.configs.flat.recommended],
  languageOptions: {
    ...pluginReact.configs.flat.recommended.languageOptions,
    globals: {
      window: true,
      document: true,
    },
  },
  plugins: {
    "react-hooks": eslintPluginReactHooks,
    "react-compiler": reactCompiler,
  },
  settings: { react: { version: "detect" } },
  rules: {
    ...eslintPluginReactHooks.configs.recommended.rules,
    "react/react-in-jsx-scope": "off",
    "react-compiler/react-compiler": "error",
  },
});

// Standalone Node scripts. They are plain .mjs run by `node`, not part of any tsconfig, so the
// type-aware rules see every value as `any` and the browser-ish default globals hide `process`
// and `console`. Scoped narrowly and additively: this block changes nothing for src/ or tests/.
const scriptsConfig = tseslint.config({
  files: ["scripts/**/*.mjs"],
  extends: [tseslint.configs.disableTypeChecked],
  languageOptions: {
    globals: { process: "readonly", console: "readonly", URL: "readonly" },
  },
  rules: {
    // A CLI script's output IS its interface.
    "no-console": "off",
  },
});

const astroConfig = tseslint.config({
  files: ["**/*.astro"],
  rules: {
    "astro/no-set-html-directive": "error",
    "astro/no-unused-css-selector": "warn",
    "astro/prefer-class-list-directive": "warn",

    // A page that holds a secret is one keystroke from shipping it. MEASURED 2026-09-12: importing
    // SUPABASE_KEY in frontmatter and passing it to a `client:load` island BUILDS FINE, leaves
    // dist/client clean, passes `npm run check:secrets` — and puts the value verbatim into the HTTP
    // response inside `<astro-island props="...">`. Astro cannot stop it: the ServerOnlyModule guard
    // is keyed on which Vite environment resolves the module, and frontmatter resolves in `ssr`.
    //
    // So this bans the first step rather than the last. It is deliberately blunt — it forbids the
    // import even where the frontmatter would only read the value server-side — because no .astro
    // file in this repo imports it today, so the restriction costs nothing and removes the whole
    // class. The output-side guard is tests/render/island-props.test.ts, which catches what a source
    // rule cannot: the same value arriving through a helper, a re-export or a spread.
    //
    // NOT covered by the type system, which is worth saying because it nearly is: `astro check`
    // does reject an undeclared prop and a field missing from the source object (measured, two
    // errors). It cannot reject a secret handed to a prop already declared `string` — and a secret
    // is a string. Passing SUPABASE_KEY to SignInForm's `serverError` type-checks today.
    "no-restricted-imports": [
      "error",
      {
        paths: [
          {
            name: "astro:env/server",
            message:
              "Do not read server secrets in .astro frontmatter: Astro serializes island props into the HTML response, so one prop away is a disclosure the bundle scan cannot see. Read it in a .ts module and export a derived, non-secret value — src/lib/config-status.ts is the pattern.",
          },
        ],
      },
    ],
  },
});

export default tseslint.config(
  includeIgnoreFile(gitignorePath),
  // Generated by `npm run db:gen-types` — never hand-edited, so never linted/formatted.
  // `.claude/` holds harness state and agent git worktrees (checked-out project copies);
  // linting those would double-report and drag in stale generated files.
  { ignores: ["src/db/database.types.ts", ".claude/**"] },
  baseConfig,
  reactConfig,
  eslintPluginAstro.configs["flat/recommended"],
  ...eslintPluginAstro.configs["flat/jsx-a11y-recommended"],
  astroConfig,
  scriptsConfig,
  eslintPluginPrettier,
);
